#!/bin/bash
 ERR=1 # or some non zero error number you want
 MAX_TRIES=4

 for (( i=1; i<=$MAX_TRIES; i++ ))
   do
     vagrant up $provider
     if [ $? -eq 0 ];then
        exit 0
     fi
     echo "vagrant up failed!"
     vagrant destroy -f
   done
echo "Too many non-sucessful tries"
exit $ERR
